spring.application.name=circuit-breaker

server.port=8800

#retry
resilience4j.retry.instances.sample-api.maxReyTryAttempts=5
resilience4j.retry.instances.sample-api.waitDuration=1s
resilience4j.retry.instances.sample-api.enableExponentialBackoff=true

#CircuitBreaker
#resilience4j.circuitbreaker.instance.sample-api.failureRateThreshold=90


#resilience4j.ratelimiter.instances.sample-api.limitForPeriod=2
#resilience4j.ratelimiter.instances.sample-api.limitRefreshPeriod=10s

resilience4j.bulkhead.instances.default.maxConcurrentCalls=10
resilience4j.bulkhead.instances.sample-api.maxConcurrentCalls=10


